version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: pdf-chat-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: securepassword123
      MONGO_INITDB_DATABASE: pdf_chat
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - pdf-chat-network

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  pdf-chat-network:
    driver: bridge